name = "cloudflare-request-server"
main = "src/index.js"
compatibility_date = "2025-10-01"
type = "javascript"
d1_databases = [
  { binding = "REQUEST_DB", database_name = "requests" }
]

[vars]
ALLOWED_ORIGINS = "http://127.0.0.1:5500"
